parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 2020
  requireConfigFile: false
extends:
  - airbnb-base
  - prettier
plugins:
  - prettier
env:
  es2020: true
  mocha: true
  node: true
  jest: true
rules:
  valid-jsdoc: warn
  func-names: error
  prettier/prettier: error
  import/extensions:
  - warn
  import/no-extraneous-dependencies:
  - "error"
  comma-dangle:
  - error
  - arrays: always-multiline
    objects: always-multiline
    imports: always-multiline
    exports: always-multiline
    functions: ignore
settings:
  import/resolver: node
