plugins:
  - prettier
  - import
env:
  es2020: true
  node: true
  jest: true
rules:
  valid-jsdoc: warn
  func-names: error
  prettier/prettier: error
  comma-dangle:
  - error
  - arrays: always-multiline
    objects: always-multiline
    imports: always-multiline
    exports: always-multiline
    functions: ignore
