compressionLevel: mixed

enableGlobalCache: false

npmPublishRegistry: https://registry.npmjs.org

packageExtensions:
  documentation@*:
    dependencies:
      micromark: '*'

yarnPath: .yarn/releases/yarn-4.9.1.cjs
