version: 2.1

# set shared defaults across jobs
defaults: &defaults
  working_directory: ~/oss-proj
  docker:
    - image: cimg/node:14.17.6

jobs:
  # checkout repo
  checkout_code:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "2f:a5:52:3f:40:bc:c1:9b:a4:1e:5b:aa:0d:9c:35:6b"
      - checkout
      - run:
          name: Record SHA
          command: echo $CIRCLE_SHA1 > .circle-sha
      - persist_to_workspace:
          root: ~/
          paths:
            - oss-proj
  # install dependencies
  install_npm_deps:
    <<: *defaults
    steps:
      - run:
          name: Record SHA
          command: echo $CIRCLE_SHA1 > .circle-sha
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - yarn-3-packages-v1-{{ checksum "yarn.lock" }}
            - yarn-3-packages-v1
      - run:
          name: Install dependencies
          command: |
            node -v
            yarn --version
            yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-3-packages-v1-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
      - save_cache:
          name: Save Backup Package Cache
          key: yarn-3-packages-v1
          paths:
            - .yarn/cache
      - persist_to_workspace:
          root: ~/
          paths:
            - oss-proj/.yarn/cache
            - oss-proj/.yarn/unplugged

  # circle needs a build step no matter what
  build:
    <<: *defaults
    steps:
      - run:
          name: Record SHA
          command: echo $CIRCLE_SHA1 > .circle-sha
      - attach_workspace:
          at: ~/

  # our verify step
  test:
    <<: *defaults
    steps:
      - run:
          name: Record SHA
          command: echo $CIRCLE_SHA1 > .circle-sha
      - attach_workspace:
          at: ~/
      - run:
          name: Test
          command: yarn test

  # publish
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: |
            git config --global user.email {GIT_AUTHOR_EMAIL};
            git config --global user.name {GIT_AUTHOR_NAME};
            yarn ci:publish;

# our workflow per v2
workflows:
  build_test_and_deploy:
    jobs:
      - checkout_code
      - install_npm_deps:
          requires:
            - checkout_code
      - build:
          requires:
            - install_npm_deps
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deploy:
          context: node
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              only: master