version: 2

# set shared defaults across jobs
defaults: &defaults
  working_directory: ~/oss-proj
  docker:
    - image: circleci/node:8.10-stretch

jobs:
  # checkout repo
  checkout_code:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "80:fc:2d:39:39:fd:17:9f:32:c6:cc:c4:28:2c:1d:d7"
      - checkout
      - run:
          name: Record SHA
          command: echo $CIRCLE_SHA1 > .circle-sha
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - oss-proj
  # install dependencies
  install_npm_deps:
    <<: *defaults
    steps:
      - run:
          name: Record SHA
          command: echo $CIRCLE_SHA1 > .circle-sha
      - attach_workspace:
          at: ./
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "./oss-proj/yarn.lock" }}
            - yarn-packages
      - run:
          name: Install dependencies
          command: cd oss-proj && yarn i
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "./oss-proj/yarn.lock" }}
          paths:
            - ./oss-proj/node_modules
      - save_cache:
          name: Save Backup Package Cache
          key: yarn-packages
          paths:
            - ./oss-proj/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - oss-proj/node_modules

  # circle needs a build step no matter what
  build:
    <<: *defaults
    steps:
      - run:
          name: Record SHA
          command: echo $CIRCLE_SHA1 > .circle-sha
      - attach_workspace:
          at: ./

  # our verify step
  test:
    <<: *defaults
    steps:
      - run:
          name: Record SHA
          command: echo $CIRCLE_SHA1 > .circle-sha
      - attach_workspace:
          at: ./
      - run:
          name: Test
          command: cd oss-proj && yarn test

  # publish
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Authenticate with NPM
          command: cd oss-proj && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: |
            git config --global user.email {GIT_AUTHOR_EMAIL};
            git config --global user.name {GIT_AUTHOR_NAME};
            cd oss-proj && yarn ci:publish;

# our workflow per v2
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - checkout_code
      - install_npm_deps:
          requires:
            - checkout_code
      - build:
          requires:
            - install_npm_deps
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deploy:
          context: node
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              only: master